[package]
name = "placementd"
version = "0.1.0"
edition = "2021"
authors = ["R Tyler Croy <rtyler@brokenco.de>"]
description = "Placement service for neutron"
readme = "README.md"
license = "LICENSE"

[dependencies]
sqlx = "0.7.3"
tide = "0.16.0"
