---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: neutron-manager
  namespace: default
spec:
  selector:
    matchLabels:
      app: manager
  replicas: 1
  template:
    metadata:
      labels:
        app: manager
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: spark-manager-config
      containers:
        - image: apache/spark:latest
          name: driver
          command: 
            - /opt/spark/sbin/start-master.sh
          env:
            - name: SPARK_NO_DAEMONIZE
              value: 'true'
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
            - containerPort: 7070
              name: driver
              protocol: TCP
            - containerPort: 6066
              name: rest
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: web
            initialDelaySeconds: 2
          volumeMounts:
            - name: config-volume
              mountPath: /opt/spark/conf/spark-defaults.conf
              subPath: spark-defaults.conf
