---
apiVersion: v1
kind: Service
metadata:
  name: spark-manager
spec:
  selector:
    app: manager
  ports:
    - name: web
      protocol: TCP
      port: 7077
      targetPort: 7077
    - name: rest
      protocol: TCP
      port: 6066
      targetPort: 6066
