# This file contains the resource to provision a development placementd inside the kubernetes test environment
---
apiVersion: v1
kind: Namespace
metadata:
  name: placementd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: placementd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: placementd
  template:
    metadata:
      labels:
        app: placementd
    spec:
      containers:
        - name: placementd
          image: ubuntu:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: RUST_LOG
              value: debug
          command:
            - /bin/sh
          args:
            - -c
            - while true; do /tmp/placementd-web; sleep 1; done
          ports:
